In [1]:
import pandas as pd
import numpy as np

In [15]:
df=pd.read_csv(r"C:\Users\bansa\OneDrive\Desktop\EduPath-India\data\merged_jee_cutoff_2018_2025.csv")

In [16]:
df.shape

(433993, 9)

In [17]:
df.columns

Index(['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender',
       'Opening Rank', 'Closing Rank', 'Round', 'Year'],
      dtype='object')

In [18]:
df.head()

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,Round,Year
0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Gender-Neutral,5057.0,6780.0,1,2018
1,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Female-only (including Supernumerary),10078.0,10789.0,1,2018
2,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OBC-NCL,Gender-Neutral,1649.0,2592.0,1,2018
3,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OBC-NCL,Female-only (including Supernumerary),4343.0,4522.0,1,2018
4,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,SC,Gender-Neutral,1054.0,1233.0,1,2018

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 433993 entries, 0 to 433992
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Institute              433993 non-null  object
 1   Academic Program Name  433992 non-null  object
 2   Quota                  433992 non-null  object
 3   Seat Type              433991 non-null  object
 4   Gender                 433990 non-null  object
 5   Opening Rank           432525 non-null  float64
 6   Closing Rank           432524 non-null  float64
 7   Round                  433993 non-null  int64
 8   Year                   433993 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 29.8+ MB

In [20]:
df.describe()

       Opening Rank  Closing Rank          Round           Year
count  4.325250e+05  4.325240e+05  433993.000000  433993.000000
mean   1.091298e+04  1.378077e+04       3.547546    2021.776517
std    3.120640e+04  4.163089e+04       1.798195       2.353832
min    1.000000e+00  1.000000e+00       1.000000    2018.000000
25%    1.218000e+03  1.485000e+03       2.000000    2020.000000
50%    3.783000e+03  4.555000e+03       4.000000    2022.000000
75%    1.010400e+04  1.221700e+04       5.000000    2024.000000
max    1.274910e+06  1.368129e+06       7.000000    2025.000000

In [21]:
df.isnull().sum()

Institute                   0
Academic Program Name       1
Quota                       1
Seat Type                   2
Gender                      3
Opening Rank             1468
Closing Rank             1469
Round                       0
Year                        0
dtype: int64

In [22]:
df=df.dropna()

In [23]:
df.shape

(432524, 9)

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df=df.drop_duplicates()

In [26]:
df.shape

(432524, 9)

In [27]:
df.columns = df.columns.str.strip().str.replace(' ', '_').str.lower()
print(df.columns)

Index(['institute', 'academic_program_name', 'quota', 'seat_type', 'gender',
       'opening_rank', 'closing_rank', 'round', 'year'],
      dtype='object')

In [28]:
df.to_csv(r"C:\Users\bansa\OneDrive\Desktop\EduPath-India\data\cleaned\jee_cleaned.csv", index=False)
print("JEE file saved!")

JEE file saved!

In [29]:
import pandas as pd
df2 = pd.read_csv(r"C:\Users\bansa\OneDrive\Desktop\EduPath-India\data\Indian_Engineering_Colleges_Dataset.csv")

In [30]:
df2.shape

(732, 12)

In [31]:
print(df2['State'].unique())
print(df2['State'].nunique())

['Tamil nadu' 'Maharashtra' 'Uttar pradesh' 'Delhi ncr' 'Andhra pradesh'
 'Karnataka' 'Telangana' 'Madhya pradesh' 'Kerala' 'Rajasthan' 'Haryana'
 'Gujarat' 'Punjab' 'West bengal' 'Orissa' 'Uttarakhand' 'Assam' 'Bihar'
 'Chhattisgarh' 'Jharkhand' 'Himachal pradesh' 'Jammu' 'Chandigarh' 'Goa'
 'Arunachal pradesh' 'Meghalaya' 'Nagaland' 'Puducherry' 'Tripura'
 'Sikkim' 'Manipur' 'Mizoram' 'Andaman' 'Dadra' 'Daman']
35

In [32]:
df2.isnull().sum()

Unnamed: 0        0
College_Name      0
State             0
UG_fee            0
PG_fee            0
Rating            0
Academic          0
Accommodation     0
Faculty           0
Infrastructure    0
Placement         0
Social_Life       0
dtype: int64

In [34]:
df2.to_csv(r"C:\Users\bansa\OneDrive\Desktop\EduPath-India\data\cleaned\private_colleges_cleaned.csv", index=False)
print("Private colleges file saved!")

Private colleges file saved!